### PR TITLE
Add multiple august 2022 lineups

### PR DESCRIPTION
**Pull request by leccelecce**

### CODE REVIEW

**Comment by leccelecce** [comment]
Hmm...might need to old off on this one. I had a load of trouble in my scraper + Spotify API validator refusing to validate artists with non-ASCII characters. I eventually solved it the warm cache script still doesn't like some of them

**Comment by dot4qu** [comment]
Will take a look at this and all others this weekend to see if I can see what's up

**Comment by leccelecce** [comment]
OK - think I've got it. The files my scraper wrote out originally to disk were UTF-8 encoded. However at some point when committing to git for this PR, it seems (judging by Notepad++) the encoding changed back to ANSI somehow. If I manually convert the file to UTF-8 then re-run the cache warm script locally, it works fine and detects the artist. A brief google suggests that there are some special cases with git I probably need to figure out.
I'm interested as to whether this "just works" reliably at your end. If you try warm cache with reading 2022, if it's working you'll get 33/33 artists, if not Måneskin will drop out.

**Comment by dot4qu** [comment]
Yeah it's going to need to be UTF-8 for that character. It fails currently for me too when I pull it since it's an unknown unicode symbol.

Looks like GitHub will do it for you if you edit and re-commit with their web interface: 
image

Or if you've already got it converted go ahead and push a new lineup for leeds and reading. I tested two of the others locally and they all look good so I'm assuming they're all good. Once merged I'll let you know if any have issues when I run them all on the prod machine

**Comment by dot4qu** [comment]
Still seeing a weird encoding for maneskin, not sure if your last commit was supposed to fix that or not

**Comment by leccelecce** [comment]
Fixed now!

**Review by dot4qu — APPROVED** [review]

**Comment by dot4qu** [comment]
All festivals deployed to prod and tested with a playlist generation, thanks for so many additions!

**Pull request merged**
